version: '3.8'

services:
  web:
    build:
      # Use Docker Buildkit for better caching and performance
      context: .
      dockerfile: Dockerfile
      args:
        - ESLINT_SKIP=true
        - NEXT_ESLINT_SKIP_VALIDATION=1
        - BUILDKIT_INLINE_CACHE=1
      # Force rebuild without using cache
      no_cache: false
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      - ESLINT_SKIP=true
      - NEXT_ESLINT_SKIP_VALIDATION=1
    # Override the logging configuration for local development
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3" 