version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ESLINT_SKIP=true
        - NEXT_ESLINT_SKIP_VALIDATION=1
        - BUILDKIT_INLINE_CACHE=1
        - NODE_ENV=production
    image: ${ECR_REPOSITORY_URI:-aurora/frontend}:${IMAGE_TAG:-latest}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - ESLINT_SKIP=true
      - NEXT_ESLINT_SKIP_VALIDATION=1
      - AWS_REGION=${AWS_REGION:-us-east-1}
      # Add other environment variables needed by your application
    logging:
      driver: "awslogs"
      options:
        awslogs-region: "${AWS_REGION:-us-east-1}"
        awslogs-group: "/ecs/aurora-frontend"
        awslogs-stream-prefix: "web"
    restart: unless-stopped
    volumes:
      - ./public:/app/public
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # ECS resource limits
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 512M

networks:
  app-network:
    driver: bridge 