import type { Metadata } from "next";
// Using local font fallback instead of Google Fonts to avoid Docker build issues
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LocaleProvider } from "../context/LocaleContext";

// Define CSS variables for fonts without attempting to fetch them
const fontVariables = {
  variable: "font-sans",
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <LocaleProvider>{children}</LocaleProvider>
      </body>
    </html>
  );
}
